These are the notes for my emacs configuration.
Excuse the mess that this file will inevitably turn into
while I get proficient with org-mode
- Kahr Kunne 22.06-2016

* Look into
Things in here are things that might improve my configuration
and that I need to look into.
** Magit
** Projectile
*** Also check out helm-projectile!
** Smartparens
*** What does it offer over paredit?
** Hippie-expand
** Tramp
*** What does it do, exactly?
** Avy
*** Differences between avy and ace-jump?
* TODO's
Things in here are one-off issues that I need to fix.
Things here are more general, issues with specific packages and functions
are to be declared where they are defined.
** TODO Make org-mode look good
*** Fonts too big
*** Weird colors
*** Fucks up line numbers
** TODO Fix workflow issue with paredit and evil-mode
** DONE Throw this whole thing on github
** TODO Line numbers on last line
** TODO Fix agressive-indent-mode
*** Looks to be related to use-package
** See also: .el files in .emacs.d

* Long term issues/ideas
Things here are not so much things you "do" as more issues that I need to
sort out in the long term.
** Think about evil-mode
*** Evil-mode by itself is great, however sometimes it clashes with emacs. I might commit to learning vanilla Emacs and ditching evil, but don't count on it
** Learn org-mode properly
** Change the structure of my config a bit more
*** Right now, some keybindings are in packages.el and some in functions-and-keybindings.el
*** There's some non-appearance config in appearance.el
*** There's some cruft in packages.el
*** There's appearance code in init.el
**** See TODO's in that file for more info
** I need to start using some things more
   All of these things are useful, I don't use them enough
*** User-defined functions
*** YASnippet
*** Expand-region
*** Evil-surround
*** Multiple-cursors
