;;; Automatically generated by ‘recentf’ on Mon Jun 18 21:00:36 2018.

(setq recentf-list
      '(
        "/home/kahr/.emacs.d/org-init.org"
        "/home/kahr/Toshokan/toshokan/old/b"
        "/home/kahr/Toshokan/toshokan/old/getallnames.py"
        "/home/kahr/Toshokan/toshokan/constants.py"
        "/home/kahr/Toshokan/toshokan/config.py"
        "/home/kahr/Toshokan/toshokan/compile.sh"
        "/home/kahr/.emacs.d/elpa/treemacs-evil-20180522.832/treemacs-evil-autoloads.el"
        "/home/kahr/Toshokan/toshokan/docs.org"
        "/home/kahr/Toshokan/toshokan/requirements.txt"
        "/home/kahr/Toshokan/toshokan/index.py"
        "/home/kahr/.emacs.d/elpa/treemacs-20180618.950/treemacs-autoloads.el"
        "/home/kahr/Toshokan/toshokan/res/js/toshokan.js"
        "/home/kahr/.emacs.d/elpa/treemacs-projectile-20180614.1021/treemacs-projectile-autoloads.el"
        "/home/kahr/.emacs.d/org-init.el"
        "/home/kahr/.emacs.d/var/recentf-save.el"
        "/home/kahr/.xinitrc"
        "/home/kahr/builds/qmk_firmware/keyboards/keyboard_project/config.h"
        "/home/kahr/builds/qmk_firmware/keyboards/keyboard_project/keyboard_project.h"
        "/home/kahr/keyboard_pins.txt"
        "/home/kahr/s2.py"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
