;;; Automatically generated by ‘recentf’ on Tue Aug 21 09:02:15 2018.

(setq recentf-list
      '(
        "/home/kahr/Toshokan/toshokan2/toshokan-api/api/recengine.py"
        "/home/kahr/Toshokan/toshokan2/toshokan-api/dbcredentials.txt"
        "/home/kahr/Toshokan/toshokan2/scraper/toshokan/toshokan/spiders/mal_person_spider.py"
        "/sudo:root@localhost:/usr/lib/syncplay/syncplay/players/mplayer.py"
        "/sudo:root@localhost:/usr/lib/syncplay/syncplay/ui/ConfigurationGetter.py"
        "/usr/lib/syncplay/syncplay/ui/ConfigurationGetter.py"
        "/usr/lib/syncplay/syncplay/clientManager.py"
        "/usr/lib/syncplay/syncplay/players/mplayer.py"
        "/sudo:root@localhost:/usr/lib/syncplay/syncplay/clientManager.py"
        "/usr/lib/syncplay/syncplay/client.py"
        "/usr/lib/syncplay/syncplayClient.py"
        "/home/kahr/Toshokan/toshokan2/toshokan-api/openapi/specification.yaml"
        "/home/kahr/Toshokan/toshokan2/toshokan-api/.gitignore"
        "/home/kahr/Toshokan/toshokan2/toshokan-api/requirements.txt"
        "/home/kahr/.emacs.d/elpa/yaml-mode-20180409.607/yaml-mode-autoloads.el"
        "/home/kahr/.emacs.d/var/recentf-save.el"
        "/home/kahr/.emacs.d/org-init.org"
        "/home/kahr/.emacs_workgroups"
        "/home/kahr/mono-theme.el"
        "/home/kahr/.emacs.d/meme-theme.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
